apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qemu-riscv64.fullname" . }}
  labels:
    {{- include "qemu-riscv64.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "qemu-riscv64.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qemu-riscv64.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: data-bin-provider
        image: busybox:1.36.1-musl
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/sh"
        args:
        - "-c"
        - "cp bin/busybox /bin-cp/; (cd /bin-cp; ln busybox sh; ln busybox ls; ln busybox cp)"
        volumeMounts:
        - mountPath: /bin-cp
          name: data-bin
      - name: data-provider
        image: {{ .Values.images.data }}
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/sh"
        args:
        - "-c"
        - "for i in `ls /data`; do cp -r /data/$i /data-cp/; done"
        volumeMounts:
        - mountPath: /bin
          name: data-bin
        - mountPath: /data-cp
          name: data
      containers:
      - name: qemu-launcher
        image: {{ .Values.images.launcher }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{ .Values.cpu.count }}
            memory: {{ .Values.memory }}
        env:
        - name: VM_CPU_FEATURES
          value: "{{ .Values.cpu.features }}"
        - name: VM_CPU_COUNT
          value: "{{ .Values.cpu.count }}"
        - name: VM_MEMORY
          value: "{{ .Values.memory }}"
        - name: VM_APPEND
          value: "{{ .Values.append }}"
        ports:
        - containerPort: 10023
          name: qemu-telnet
        volumeMounts:
        - mountPath: /data
          name: data
      - name: qemu-console
        image: {{ .Values.images.console }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: qemu-console
      volumes:
      - name: data-bin
        emptyDir: {}
      - name: data
        emptyDir: {}
