images:
  launcher: carvicsforth/qemu-riscv64-launcher:1.2.0
  launcherRVV071: carvicsforth/qemu-riscv64-launcher-rvv-0.7.1:1.2.0
  console: carvicsforth/qemu-riscv64-console:1.2.0
  data: carvicsforth/qemu-riscv64-ubuntu:22.04-1

service:
  type: LoadBalancer
  port: 8080

cpu:
  features:
  count: 2
memory: 2048
append:

knot:
  enabled: false
  hostname: qemu-riscv64.example.com
  metadata:
    images.launcher:
      hidden: true
    images.console:
      hidden: true
    images.data:
      title: OS image
      choices:
      - "carvicsforth/qemu-riscv64-ubuntu:22.04-1"
      - "carvicsforth/qemu-riscv64-buildroot:00709af-1"
      - "carvicsforth/qemu-riscv64-buildroot-rvv-0.7.1:954aeb7-1"
    service.type:
      hidden: true
    service.port:
      hidden: true
    cpu.features:
      hidden: true
    cpu.count:
      title: CPU count
    append:
      hidden: true
